### ISSUE TITLE
Docker playbook does not bring up Docker daemon

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/ansible-playbooks#83]
```
$ docker login -u ...
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
```

Maybe this shouldn't be added - let's discuss tomorrow...

**Comment by jbeemster** [comment]
The playbook does bring up the daemon but only under root currently.  From the documentation we can make a docker group however all the commands used by this group are still the same as root.  According to the documentation:

### Create a Docker group
The docker daemon binds to a Unix socket instead of a TCP port. By default that Unix socket is owned by the user root and other users can access it with sudo. For this reason, docker daemon always runs as the root user.

To avoid having to use sudo when you use the docker command, create a Unix group called docker and add users to it. When the docker daemon starts, it makes the ownership of the Unix socket read/writable by the docker group.

__Warning: The docker group is equivalent to the root user; For details on how this impacts security in your system, see Docker Daemon Attack Surface for details.__

---

So I can go ahead and make a docker group and add the provisioning host to said group but it would yield the same security impact as just using sudo.

**Comment by alexanderdean** [comment]
Thanks for explaining @jbeemster - I was just being stupid. sudo it is!
